environment:
    matrix:
        - nodejs_version: "6"
        - nodejs_version: "7"
        - nodejs_version: "8"
        - nodejs_version: "9"

install:
    - ps: echo 1
    - ps: Install-Product node $env:nodejs_version
    - ps: yarn

test_script:
    - ps: yarn lint
    - ps: yarn flow
    - ps: yarn test
