environment:
    matrix:
        - nodejs_version: "6"
        - nodejs_version: "7"
        - nodejs_version: "8"
        - nodejs_version: "9"

install:
    - ps: Install-Product node $env:nodejs_version
    - yarn

test_script:
    - yarn lint
    - yarn flow
    - yarn test
