// flow-typed signature: 115a51f963d512ade414a0e3875b76e1
// flow-typed version: <<STUB>>/captain-git-hook_v^2.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'captain-git-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'captain-git-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'captain-git-hook/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'captain-git-hook/index' {
  declare module.exports: $Exports<'captain-git-hook'>;
}
declare module 'captain-git-hook/index.js' {
  declare module.exports: $Exports<'captain-git-hook'>;
}
declare module 'captain-git-hook/test/index.js' {
  declare module.exports: $Exports<'captain-git-hook/test/index'>;
}
